/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

/**
 *
 * @author paren
 */
public class Front_Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Front_Calculadora
     */
    public Front_Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botaoPorcetagem = new javax.swing.JButton();
        botaoDividir = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        botaoMultiplicar = new javax.swing.JButton();
        botaosubtrair = new javax.swing.JButton();
        botaoSomar = new javax.swing.JButton();
        botaoNove = new javax.swing.JButton();
        botaoOito = new javax.swing.JButton();
        botaoSete = new javax.swing.JButton();
        botaoCinco = new javax.swing.JButton();
        botaoSeis = new javax.swing.JButton();
        botaoQuatro = new javax.swing.JButton();
        botaoDois = new javax.swing.JButton();
        botaoTres = new javax.swing.JButton();
        botaoPonto = new javax.swing.JButton();
        botaoUm = new javax.swing.JButton();
        botaoZero = new javax.swing.JButton();
        botaoIgual = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Calculadora");

        botaoPorcetagem.setText("%");
        botaoPorcetagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPorcetagemActionPerformed(evt);
            }
        });

        botaoDividir.setText("/");
        botaoDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDividirActionPerformed(evt);
            }
        });

        botaoLimpar.setText("AC");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoMultiplicar.setText("x");
        botaoMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMultiplicarActionPerformed(evt);
            }
        });

        botaosubtrair.setText("-");
        botaosubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaosubtrairActionPerformed(evt);
            }
        });

        botaoSomar.setText("+");
        botaoSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSomarActionPerformed(evt);
            }
        });

        botaoNove.setText("9");
        botaoNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNoveActionPerformed(evt);
            }
        });

        botaoOito.setText("8");
        botaoOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOitoActionPerformed(evt);
            }
        });

        botaoSete.setText("7");
        botaoSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSeteActionPerformed(evt);
            }
        });

        botaoCinco.setText("5");
        botaoCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCincoActionPerformed(evt);
            }
        });

        botaoSeis.setText("6");
        botaoSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSeisActionPerformed(evt);
            }
        });

        botaoQuatro.setText("4");
        botaoQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoQuatroActionPerformed(evt);
            }
        });

        botaoDois.setText("2");
        botaoDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDoisActionPerformed(evt);
            }
        });

        botaoTres.setText("3");
        botaoTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTresActionPerformed(evt);
            }
        });

        botaoPonto.setText(".");
        botaoPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPontoActionPerformed(evt);
            }
        });

        botaoUm.setText("1");
        botaoUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoUmActionPerformed(evt);
            }
        });

        botaoZero.setText("0");
        botaoZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoZeroActionPerformed(evt);
            }
        });

        botaoIgual.setText("=");
        botaoIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIgualActionPerformed(evt);
            }
        });

        txtResultado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoUm, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoZero, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoDois, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoTres, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botaoOito, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoNove, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaosubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoPorcetagem, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(botaoDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPorcetagem, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaosubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSete, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoNove, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoOito, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoDois, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoTres, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoUm, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoZero, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Num1Num2 num = new Num1Num2();
    executando exe = new executando();
    String num1, num2, sinal;    
    Double num01, num02, resp, num4;
    boolean somar = false; boolean subtrair = false; boolean multiplicar = false;
    boolean dividir = false; boolean calculo = false; boolean porcentagem;
    double conta1,conta2 ;
    String contaTxt1, contaTxt2, resp1;
    int j = 0;
    private void botaoZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoZeroActionPerformed
            if(calculo == true){
        resp1 = " "; 
            if(somar == true){
                if(contaTxt2 == null){                
                txtResultado.setText(null);    
                txtResultado.setText(txtResultado.getText() + "0");        
                contaTxt2 = txtResultado.getText();                    
                txtResultado.setText(null);    
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);
            }
                else if(contaTxt2 != null){            
                txtResultado.setText(contaTxt2 + "0");                                
                contaTxt2 = txtResultado.getText();
                txtResultado.setText(null);        
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(subtrair == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "0");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "0");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(dividir == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "0");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "0");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
                else if(multiplicar == true){
                    if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "0");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                    else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "0");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
        }
        else{
        txtResultado.setText(txtResultado.getText() + "0");                        
        contaTxt1 = txtResultado.getText();
        conta1 = Double.parseDouble(contaTxt1);
        }
        
    }//GEN-LAST:event_botaoZeroActionPerformed

    private void botaoUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoUmActionPerformed
                  if(calculo == true){
        resp1 = " "; 
            if(somar == true){
                if(contaTxt2 == null){                
                txtResultado.setText(null);    
                txtResultado.setText(txtResultado.getText() + "1");        
                contaTxt2 = txtResultado.getText();                    
                txtResultado.setText(null);    
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);
            }
                else if(contaTxt2 != null){            
                txtResultado.setText(contaTxt2 + "1");                                
                contaTxt2 = txtResultado.getText();
                txtResultado.setText(null);        
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(subtrair == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "1");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "1");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(dividir == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "1");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "1");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
                else if(multiplicar == true){
                    if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "1");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                    else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "1");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
        }
        else{
        txtResultado.setText(txtResultado.getText() + "1");                        
        contaTxt1 = txtResultado.getText();
        conta1 = Double.parseDouble(contaTxt1);
        }
        
        
    }//GEN-LAST:event_botaoUmActionPerformed

    private void botaoDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDoisActionPerformed
        if(calculo == true){
        resp1 = " "; 
            if(somar == true){
                if(contaTxt2 == null){                
                txtResultado.setText(null);    
                txtResultado.setText(txtResultado.getText() + "2");        
                contaTxt2 = txtResultado.getText();                    
                txtResultado.setText(null);    
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);
            }
                else if(contaTxt2 != null){            
                txtResultado.setText(contaTxt2 + "2");                                
                contaTxt2 = txtResultado.getText();
                txtResultado.setText(null);        
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(subtrair == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "2");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "2");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(dividir == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "2");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "2");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
                else if(multiplicar == true){
                    if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "2");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                    else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "2");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
        }
        else{
        txtResultado.setText(txtResultado.getText() + "2");                        
        contaTxt1 = txtResultado.getText();
        conta1 = Double.parseDouble(contaTxt1);
        }
        
    }//GEN-LAST:event_botaoDoisActionPerformed

    private void botaoTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTresActionPerformed
        
        if(calculo == true){
        resp1 = " ";
            if(somar == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "3");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){        
                    txtResultado.setText(null);    
                    txtResultado.setText(contaTxt2 + "3");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }                
            }
            else if(subtrair == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "3");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "3");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(dividir == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "3");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "3");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(multiplicar == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "3");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "3");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
        }
        else{
        txtResultado.setText(txtResultado.getText() + "3");                        
        contaTxt1 = txtResultado.getText();
        conta1 = Double.parseDouble(contaTxt1);
        }
    }//GEN-LAST:event_botaoTresActionPerformed

    private void botaoQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoQuatroActionPerformed
        if(calculo == true){
        resp1 = " "; 
            if(somar == true){
                if(contaTxt2 == null){                
                txtResultado.setText(null);    
                txtResultado.setText(txtResultado.getText() + "4");        
                contaTxt2 = txtResultado.getText();                    
                txtResultado.setText(null);    
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);
            }
                else if(contaTxt2 != null){            
                txtResultado.setText(contaTxt2 + "4");                                
                contaTxt2 = txtResultado.getText();
                txtResultado.setText(null);        
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(subtrair == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "4");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "4");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(dividir == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "4");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "4");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
                else if(multiplicar == true){
                    if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "4");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                    else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "4");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
        }
        else{
        txtResultado.setText(txtResultado.getText() + "4");                        
        contaTxt1 = txtResultado.getText();
        conta1 = Double.parseDouble(contaTxt1);
        }
        
    }//GEN-LAST:event_botaoQuatroActionPerformed

    private void botaoCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCincoActionPerformed
        if(calculo == true){
        resp1 = " "; 
            if(somar == true){
                if(contaTxt2 == null){                
                txtResultado.setText(null);    
                txtResultado.setText(txtResultado.getText() + "5");        
                contaTxt2 = txtResultado.getText();                    
                txtResultado.setText(null);    
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);
            }
                else if(contaTxt2 != null){            
                txtResultado.setText(contaTxt2 + "5");                                
                contaTxt2 = txtResultado.getText();
                txtResultado.setText(null);        
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(subtrair == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "5");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "5");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(dividir == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "5");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "5");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
                else if(multiplicar == true){
                    if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "5");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                    else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "5");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
        }
        else{
        txtResultado.setText(txtResultado.getText() + "5");                        
        contaTxt1 = txtResultado.getText();
        conta1 = Double.parseDouble(contaTxt1);
        }
        
    }//GEN-LAST:event_botaoCincoActionPerformed

    private void botaoSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSeisActionPerformed
        if(calculo == true){
        resp1 = " "; 
            if(somar == true){
                if(contaTxt2 == null){                
                txtResultado.setText(null);    
                txtResultado.setText(txtResultado.getText() + "6");        
                contaTxt2 = txtResultado.getText();                    
                txtResultado.setText(null);    
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);
            }
                else if(contaTxt2 != null){            
                txtResultado.setText(contaTxt2 + "6");                                
                contaTxt2 = txtResultado.getText();
                txtResultado.setText(null);        
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(subtrair == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "6");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "6");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(dividir == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "6");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "6");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
                else if(multiplicar == true){
                    if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "6");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                    else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "6");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
        }
        else{
        txtResultado.setText(txtResultado.getText() + "6");                        
        contaTxt1 = txtResultado.getText();
        conta1 = Double.parseDouble(contaTxt1);
        }
        
    }//GEN-LAST:event_botaoSeisActionPerformed

    private void botaoSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSeteActionPerformed
       if(calculo == true){
        resp1 = " "; 
            if(somar == true){
                if(contaTxt2 == null){                
                txtResultado.setText(null);    
                txtResultado.setText(txtResultado.getText() + "7");        
                contaTxt2 = txtResultado.getText();                    
                txtResultado.setText(null);    
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);
            }
                else if(contaTxt2 != null){            
                txtResultado.setText(contaTxt2 + "7");                                
                contaTxt2 = txtResultado.getText();
                txtResultado.setText(null);        
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(subtrair == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "7");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "7");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(dividir == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "7");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "7");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
                else if(multiplicar == true){
                    if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "7");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                    else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "7");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
        }
        else{
        txtResultado.setText(txtResultado.getText() + "7");                        
        contaTxt1 = txtResultado.getText();
        conta1 = Double.parseDouble(contaTxt1);
        }
        
    }//GEN-LAST:event_botaoSeteActionPerformed

    private void botaoOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOitoActionPerformed
       if(calculo == true){
        resp1 = " "; 
            if(somar == true){
                if(contaTxt2 == null){                
                txtResultado.setText(null);    
                txtResultado.setText(txtResultado.getText() + "8");        
                contaTxt2 = txtResultado.getText();                    
                txtResultado.setText(null);    
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);
            }
                else if(contaTxt2 != null){            
                txtResultado.setText(contaTxt2 + "8");                                
                contaTxt2 = txtResultado.getText();
                txtResultado.setText(null);        
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(subtrair == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "8");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "8");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(dividir == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "8");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "8");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
                else if(multiplicar == true){
                    if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "8");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                    else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "8");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
        }
        else{
        txtResultado.setText(txtResultado.getText() + "8");                        
        contaTxt1 = txtResultado.getText();
        conta1 = Double.parseDouble(contaTxt1);
        }
        
       
    }//GEN-LAST:event_botaoOitoActionPerformed

    private void botaoNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNoveActionPerformed
       if(calculo == true){
        resp1 = " "; 
            if(somar == true){
                if(contaTxt2 == null){                
                txtResultado.setText(null);    
                txtResultado.setText(txtResultado.getText() + "9");        
                contaTxt2 = txtResultado.getText();                    
                txtResultado.setText(null);    
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);
            }
                else if(contaTxt2 != null){            
                txtResultado.setText(contaTxt2 + "9");                                
                contaTxt2 = txtResultado.getText();
                txtResultado.setText(null);        
                txtResultado.setText( contaTxt1+ " + " + contaTxt2);                                        
                conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(subtrair == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "9");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "9");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " - " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
            else if(dividir == true){
                if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "9");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "9");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " / " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
                else if(multiplicar == true){
                    if(contaTxt2 == null){                
                    txtResultado.setText(null);    
                    txtResultado.setText(txtResultado.getText() + "9");        
                    contaTxt2 = txtResultado.getText();                    
                    txtResultado.setText(null);    
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);
                }
                    else if(contaTxt2 != null){            
                    txtResultado.setText(contaTxt2 + "9");                                
                    contaTxt2 = txtResultado.getText();
                    txtResultado.setText(null);        
                    txtResultado.setText( contaTxt1+ " * " + contaTxt2);                                        
                    conta2 = Double.parseDouble(contaTxt2);                        
                }
            }
        }
        else{
        txtResultado.setText(txtResultado.getText() + "9");                        
        contaTxt1 = txtResultado.getText();
        conta1 = Double.parseDouble(contaTxt1);
        }
        
    }//GEN-LAST:event_botaoNoveActionPerformed

    private void botaoMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMultiplicarActionPerformed
        sinal = "*";
        multiplicar = true;
        calculo = true;
        txtResultado.setText(txtResultado.getText() + " * ");                
        
    }//GEN-LAST:event_botaoMultiplicarActionPerformed

    private void botaosubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaosubtrairActionPerformed
        subtrair = true;  
        calculo = true;
        txtResultado.setText(txtResultado.getText() + " - ");  
    }//GEN-LAST:event_botaosubtrairActionPerformed
    
    private void botaoSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSomarActionPerformed
        sinal="+";
        somar = true;  
        calculo = true;
        txtResultado.setText(txtResultado.getText() + " + ");                                        
    }//GEN-LAST:event_botaoSomarActionPerformed

    private void botaoDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDividirActionPerformed
        dividir = true;  
        calculo = true;
        txtResultado.setText(txtResultado.getText() + " / "); 
    }//GEN-LAST:event_botaoDividirActionPerformed

    private void botaoPorcetagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPorcetagemActionPerformed
        num1 = txtResultado.getText();
        txtResultado.setText(" ");                   
        sinal = "Porcetagem";
        porcentagem = true;         
    }//GEN-LAST:event_botaoPorcetagemActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        txtResultado.setText(" ");
        somar = false; subtrair = false; calculo = false; dividir = false;
        multiplicar = false;                
        num.setNum1(0.0);
        num.setNum2(0.0);        
        contaTxt1 = " ";
        contaTxt2 = " ";
        conta1 = 0;
        conta2 = 0;
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIgualActionPerformed
        txtResultado.setText(null);        
        num01 = conta1;
        num02 = conta2;        
        if(somar == true){
        resp = num01 + num02;
        resp1 = Double.toString(resp);
        txtResultado.setText(resp1);                       
        conta1 = resp;
        conta2 = 0;
        contaTxt2 = null;
        contaTxt1 = Double.toString(resp);         
        resp1 = null;
        somar = false;
        }
        else if(subtrair == true){
        resp = num01 - num02;
        resp1 = Double.toString(resp);
        txtResultado.setText(resp1);                               
        conta1 = resp;
        conta2 = 0;
        contaTxt2 = null;
        contaTxt1 = Double.toString(resp);
        subtrair = false;
        }
        else if(dividir == true){
        resp = num01 / num02;
        resp1 = Double.toString(resp);
        txtResultado.setText(resp1);                       
        conta1 = resp;
        conta2 = 0;
        contaTxt2 = null;
        contaTxt1 = Double.toString(resp);
        dividir = false;
        }
        else if(multiplicar == true){
        resp = num01 * num02;
        resp1 = Double.toString(resp);
        txtResultado.setText(resp1);                       
        conta1 = resp;
        conta2 = 0;
        contaTxt2 = null;
        contaTxt1 = resp1;
        resp = null;
        multiplicar = false;
        }
        /*num1 = conta1[0];
        num2 = conta1[1];
        num01 = Double.parseDouble(num1);
        num02 = Double.parseDouble(num2);
        if(somar == true){             
            num.setNum1(num1);
            num.setNum1(num2);
            txtResultado.setText(exe.calculoSomar(num.getNum1(), num.getNum2())+" ");
            somar = false;
        } */   
    }//GEN-LAST:event_botaoIgualActionPerformed

    private void botaoPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPontoActionPerformed
        txtResultado.setText(txtResultado.getText() +".");
    }//GEN-LAST:event_botaoPontoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Front_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Front_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Front_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Front_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Front_Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCinco;
    private javax.swing.JButton botaoDividir;
    private javax.swing.JButton botaoDois;
    private javax.swing.JButton botaoIgual;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoMultiplicar;
    private javax.swing.JButton botaoNove;
    private javax.swing.JButton botaoOito;
    private javax.swing.JButton botaoPonto;
    private javax.swing.JButton botaoPorcetagem;
    private javax.swing.JButton botaoQuatro;
    private javax.swing.JButton botaoSeis;
    private javax.swing.JButton botaoSete;
    private javax.swing.JButton botaoSomar;
    private javax.swing.JButton botaoTres;
    private javax.swing.JButton botaoUm;
    private javax.swing.JButton botaoZero;
    private javax.swing.JButton botaosubtrair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
